Apply suggestions from code review
> I'm sorry if the formatting here is strange - GitHub changes things and I don't trust them anymore.😭

This is quite nice, but I think a fair bit of things still need to be done before this PR will be stable enough to merge. I'm excited for this one because WebGPU is cool.

<details>
<summary>We need a native WebGPU library</summary>

Below (and in the GitHub Actions for this PR), you can see that it compiles just fine with Emscripten because it comes packaged with WebGPU. On the other hand, the native compilation fails because we don't have an accessible library for native code. I'm currently looking into [Dawn](https://github.com/google/dawn) for this support, but I don't like the way they expect their library to be installed. Hopefully, I can find a clean solution for using their code.

```cpp
ryan@Ryans-PC:~/projects/Img2Num$ ./img2num sh
root@cee4953c0518:/usr/src/app# rm -rf build build-wasm/
root@cee4953c0518:/usr/src/app# emcmake cmake -B build-wasm
configure: cmake -B build-wasm -DCMAKE_TOOLCHAIN_FILE=/opt/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_CROSSCOMPILING_EMULATOR=/opt/emsdk/node/22.16.0_64bit/bin/node
-- Core library configured with /usr/src/app/core/src/img2num/Error.cpp;/usr/src/app/core/src/internal/SavitskyGolay.cpp;/usr/src/app/core/src/internal/bezier.cpp;/usr/src/app/core/src/internal/bilateral_filter.cpp;/usr/src/app/core/src/internal/bilateral_filter_gpu.cpp;/usr/src/app/core/src/internal/contours.cpp;/usr/src/app/core/src/internal/fft_iterative.cpp;/usr/src/app/core/src/internal/graph.cpp;/usr/src/app/core/src/internal/image_utils.cpp;/usr/src/app/core/src/internal/kmeans.cpp;/usr/src/app/core/src/internal/kmeans_gpu.cpp;/usr/src/app/core/src/internal/labels_to_svg.cpp;/usr/src/app/core/src/internal/node.cpp
-- WASM module configured: img2num_wasm
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/app/build-wasm
root@cee4953c0518:/usr/src/app# cmake -B build
-- The CXX compiler identification is GNU 10.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Core library configured with /usr/src/app/core/src/img2num/Error.cpp;/usr/src/app/core/src/internal/SavitskyGolay.cpp;/usr/src/app/core/src/internal/bezier.cpp;/usr/src/app/core/src/internal/bilateral_filter.cpp;/usr/src/app/core/src/internal/bilateral_filter_gpu.cpp;/usr/src/app/core/src/internal/contours.cpp;/usr/src/app/core/src/internal/fft_iterative.cpp;/usr/src/app/core/src/internal/graph.cpp;/usr/src/app/core/src/internal/image_utils.cpp;/usr/src/app/core/src/internal/kmeans.cpp;/usr/src/app/core/src/internal/kmeans_gpu.cpp;/usr/src/app/core/src/internal/labels_to_svg.cpp;/usr/src/app/core/src/internal/node.cpp
-- The C compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/app/build
root@cee4953c0518:/usr/src/app# cmake --build build-wasm/
Scanning dependencies of target core_obj
[  6%] Building CXX object core/CMakeFiles/core_obj.dir/src/img2num/Error.cpp.o
[ 13%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/SavitskyGolay.cpp.o
[ 20%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/bezier.cpp.o
[ 26%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/bilateral_filter.cpp.o
[ 33%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/bilateral_filter_gpu.cpp.o
[ 40%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/contours.cpp.o
[ 46%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/fft_iterative.cpp.o
[ 53%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/graph.cpp.o
[ 60%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/image_utils.cpp.o
[ 66%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/kmeans.cpp.o
[ 73%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/kmeans_gpu.cpp.o
[ 80%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/labels_to_svg.cpp.o
[ 86%] Building CXX object core/CMakeFiles/core_obj.dir/src/internal/node.cpp.o
[ 86%] Built target core_obj
Scanning dependencies of target img2num_wasm
[ 93%] Building CXX object bindings/js/CMakeFiles/img2num_wasm.dir/src/wasm_wrapper.cpp.o
[100%] Linking CXX executable ../../../packages/js/build-wasm/index.js
[100%] Built target img2num_wasm
root@cee4953c0518:/usr/src/app# cmake --build build/
Scanning dependencies of target Img2Num
[  4%] Building CXX object core/CMakeFiles/Img2Num.dir/src/img2num/Error.cpp.o
[  9%] Building CXX object core/CMakeFiles/Img2Num.dir/src/internal/SavitskyGolay.cpp.o
[ 14%] Building CXX object core/CMakeFiles/Img2Num.dir/src/internal/bezier.cpp.o
[ 19%] Building CXX object core/CMakeFiles/Img2Num.dir/src/internal/bilateral_filter.cpp.o
In file included from /usr/src/app/core/include/internal/bilateral_filter_gpu.h:6,
                 from /usr/src/app/core/src/internal/bilateral_filter.cpp:10:
/usr/src/app/core/include/internal/gpu.h:4:10: fatal error: webgpu/webgpu_cpp.h: No such file or directory
    4 | #include <webgpu/webgpu_cpp.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [core/CMakeFiles/Img2Num.dir/build.make:121: core/CMakeFiles/Img2Num.dir/src/internal/bilateral_filter.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:176: core/CMakeFiles/Img2Num.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2
root@cee4953c0518:/usr/src/app#
```

</summary>

A lot of this code is copied and pasted into the WebGPU implementation. Duplicated code is very bad, so please will you create reusable code to avoid this,

Additionally, please remove all occurrences of std::cout when the PR is ready to be merged. There are so many things to get done that I just haven't had the chance to make a debug utility for Img2Num that would allow us to do that.

Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>